name: warewarden

volumes:
  warewarden-data:

services:
  postgres-service:
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_DB=${DB_PATH:?error}
      - POSTGRES_USER=${DB_USERNAME:?error}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?error}
    ports:
      - "5432:5432"
    volumes:
      - .warewarden-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  api-service:
    build:
      context: ./warewarden_backend
      dockerfile: Dockerfile
    depends_on:
      postgres-service:
        condition: service_healthy
    environment:
      - APP_CONFIG__DB__USERNAME=${DB_USERNAME:?error}
      - APP_CONFIG__DB__PASSWORD=${DB_PASSWORD:?error}
      - APP_CONFIG__DB__PATH=${DB_PATH:?error}
      - APP_CONFIG__DB__HOST=${DB_HOST:?error}
      - APP_CONFIG__DB__PORT=${DB_PORT:?error}
      - APP_CONFIG__DB__ECHO=${DB_ECHO:?error}
      - APP_CONFIG__DB__ECHO_POOL=${DB_ECHO_POOL:?error}
      - APP_CONFIG__DB__POOL_SIZE=${DB_POOL_SIZE:?error}
      - APP_CONFIG__DB__MAX_OVERFLOW=${DB_MAX_OVERFLOW:?error}
      - APP_CONFIG__RUN__HOST=${API_RUN_HOST:?error}
      - APP_CONFIG__RUN__PORT=${API_RUN_PORT:?error}
    volumes:
      - ./warewarden_backend:/src
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health/"]
      interval: 10s
      timeout: 5s
    restart: always