name: warewarden

volumes:
  warewarden-data:

services:
  postgres-service:
    image: postgres:17.2-alpine3.21
    env_file:
      - ./warewarden_backend/warewarden_api/.env
    environment:
      - POSTGRES_DB=$${APP_CONFIG__DB__PATH}
      - POSTGRES_USER=$${APP_CONFIG__DB__USERNAME}
      - POSTGRES_PASSWORD=$${APP_CONFIG__DB__PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - .warewarden-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  api-service:
    build:
      context: ./warewarden_backend
      dockerfile: Dockerfile
    depends_on:
      postgres-service:
        condition: service_healthy
    env_file:
      - ./warewarden_backend/warewarden_api/.env
    volumes:
      - ./warewarden_backend:/src
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health/"]
      interval: 10s
      timeout: 5s
    restart: always